name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.20'

    - name: Check Go version
      run: go version

    - name: Install dependencies
      run: go mod tidy

    - name: Build the Go app
      run: CGO_ENABLED=1 go build -o main .

    - name: Run tests
      run: go test ./...

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      run: |
        docker build . -t ${{ secrets.DOCKER_USERNAME }}/crud-app:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/crud-app:latest

    - name: Set up Minikube
      uses: medyagh/setup-minikube@latest
      with:
        minikube-version: 'latest'
        driver: docker

    - name: Start Minikube
      run: minikube start --driver=docker

    - name: Set up Kubectl
      uses: azure/setup-kubectl@v1
      with:
        version: 'v1.21.0'

    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f k8s/deployment-and-service.yaml

    - name: Check Deployment Status
      run: |
        kubectl get pods -o wide
        kubectl get services -o wide
        kubectl describe deployment deployments
        kubectl describe service services

    - name: Get all resources
      run: |
        kubectl get all
